### ISSUE TITLE
Solving PONG

### ISSUE THREAD

**Issue by tobiaswuerth** [tomatoeater/Atari-DQN#1]
Hi, thanks for your code.

I managed to install and run it locally, but am unable to solve pong with your code.
You mentioned that it does not reliably solve pong.

How many attempts did you need to get a successful run?

**Comment by iewug** [comment]
I'm not a guy studying reinforcement learning. This is just my coursework. It has to be said that Pong was successfully trained when I first wrote the code, but after I polished my code it could no longer be trained. I am really sorry for bad performance on Pong.

**Comment by tobiaswuerth** [comment]
Funny enough, after running it for like 5 times it finally managed to solve it. I'm wondering what the issue is which makes it unreliable. The only thing I can think of is lucky starting configuration or lucky random actions which allow the algorithm to learn faster. Anyhow, thanks for providing the code :)

**Comment by iewug** [comment]
Glad to hear that 👍
