### ISSUE TITLE
你好,请问模型训练的速度如何?

### ISSUE THREAD

**Issue by jzzzf** [tomatoeater/Atari-DQN#2]
python main.py --env-name breakout --model dqn --epoch 10001 --eval-cycle 500
我在4090上训练近一个小时没有完成,想问下大概需要的用时

**Comment by iewug** [comment]
我记得breakout应该不难训的吧，你看我的图三四千个epoch就差不多了。训练多久我还真记不得了， 倒是pong特别难训，这东西训不出就ctrlc再重头来一遍
