### ISSUE TITLE
Reproducibility of the Pong result

### ISSUE THREAD

**Issue by AllenNCC** [tomatoeater/Atari-DQN#3]
Hi, 

Thanks for sharing the code! 

Quick question: do you find the training results reproducible? I'm training the rl network for PONG using your code and the parameters provided, however, the results varies a lot from trial to trial, some converges, some doesn't. I wonder if you also see this?

Thanks!

**Comment by iewug** [comment]
Yes, you are right. PONG often does not converge in my code.
